// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdyftqkcbzwwukqbxffo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkeWZ0cWtjYnp3d3VrcWJ4ZmZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MTk3NzMsImV4cCI6MjA1NjQ5NTc3M30.n6PFNEMYXxiRoKHPCDjdiMgC-p6yYiBtNXCoGCOuwVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);